name: Tryour OpenGL

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: edwinRNDR/setup-opengl@v9
      - name: Test glxinfo
        run: |
          xvfb-run glxinfo
